# -*- coding: utf-8 -*-

from time import sleep
from appium import webdriver

desired_caps = {}
desired_caps['appium-version'] = '1.6.3'
desired_caps['platformName'] = 'Android'
desired_caps['platformVersion'] = '4.4.2'
desired_caps['deviceName'] = '6&22430518&1&0001'
desired_caps['appPackage'] = 'cn.com.pcgroup.magazine'
desired_caps['appActivity'] = '.module.loading.LoadingActivity'
desired_caps['noReset'] = 'true'


# 打开Appium服务器，start server后，尝试启动被测App
driver = webdriver.Remote('http://127.0.0.1:4723/wd/hub', desired_caps)
sleep(5)
'''
f = open("居家杂志1.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
driver.find_element_by_xpath("//*[@text='攻略']").click()
sleep(5)
f = open("居家杂志2.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
driver.tap([(30, 110)], 1)
sleep(3)
driver.find_element_by_xpath("//*[@text='好物']").click()
sleep(5)
f = open("居家杂志3.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
driver.tap([(30, 110)], 1)
sleep(3)
driver.find_element_by_xpath("//*[@text='看图']").click()
sleep(5)
f = open("居家杂志4.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
driver.tap([(30, 110)], 1)
sleep(3)
driver.find_element_by_xpath("//*[@text='设计师']").click()
sleep(20)
f = open("居家杂志5.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
driver.tap([(30, 110)], 1)
sleep(3)
driver.find_element_by_xpath("//*[@text='活动']").click()
sleep(5)
f = open("居家杂志6.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
driver.tap([(30, 110)], 1)
sleep(3)
driver.tap([(230, 1647)], 1)
sleep(5)
f = open("居家杂志7.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
driver.tap([(440, 1647)], 1)
sleep(5)
f = open("居家杂志8.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
driver.tap([(650, 1647)], 1)
sleep(5)
f = open("居家杂志9.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
'''
driver.tap([(860, 1647)], 1)
sleep(5)
'''
f = open("居家杂志10.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
driver.find_element_by_xpath("//*[@text='会员福利']").click()
sleep(5)
f = open("居家杂志11.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
driver.tap([(30, 110)], 1)
sleep(3)
driver.find_element_by_xpath("//*[@text='兑换积分']").click()
sleep(5)
f = open("居家杂志12.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
driver.tap([(30, 110)], 1)
sleep(3)
driver.find_element_by_xpath("//*[@text='会员福利']").click()
sleep(3)
driver.tap([(1, 1633)], 1)
sleep(5)
f = open("居家杂志13.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
driver.tap([(30, 110)], 1)
sleep(3)
driver.tap([(30, 110)], 1)
sleep(3)
driver.find_element_by_xpath("//*[@text='设置']").click()
sleep(5)
f = open("居家杂志14.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
driver.find_element_by_xpath("//*[@text='意见反馈']").click()
sleep(5)
f = open("居家杂志15.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
driver.tap([(30, 110)], 1)
sleep(3)
driver.find_element_by_xpath("//*[@text='关于我们']").click()
sleep(5)
f = open("居家杂志16.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
driver.tap([(30, 110)], 1)
sleep(3)
driver.tap([(30, 110)], 1)
sleep(3)
'''
driver.find_element_by_xpath("//*[@text='获取积分']").click()
sleep(5)
f = open("居家杂志17.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
driver.find_element_by_xpath("//*[@text='注册']").click()
sleep(5)
f = open("居家杂志18.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
driver.tap([(103, 748)], 1)
sleep(5)
f = open("居家杂志19.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
sleep(5)
driver.tap([(30, 110)], 1)
sleep(3)
driver.tap([(30, 110)], 1)
sleep(3)
driver.find_element_by_xpath("//*[@text='忘记密码?']").click()
f = open("居家杂志20.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
driver.quit()
