# -*- coding: utf-8 -*-

from time import sleep
from appium import webdriver

desired_caps = {}
desired_caps['automationName'] = 'XCUITest'
desired_caps['platformName'] = 'iOS'
desired_caps['platformVersion'] = '11.2.5'
desired_caps['deviceName'] = 'iPhone 5s'
desired_caps['bundleId'] = 'com.alipay.iphoneclient'
desired_caps['udid'] = '0f5fbbaf273ea90dce8408987e215817b66146af'
desired_caps['newCommandTimeout'] = 3600  # 1 hour
desired_caps['xcodeOrgId'] = '俊宇 裴'
desired_caps['xcodeSigningId'] = 'iPhone Developer'


# 打开Appium服务器，start server后，尝试启动被测App
driver = webdriver.Remote('http://127.0.0.1:4723/wd/hub', desired_caps)
f = open("支付宝1.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
sleep(1)
driver.find_element_by_name("余额宝").click()
f = open("支付宝2.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
sleep(1)
driver.find_element_by_name("AUBarButtonItemButton_back").click()
driver.find_element_by_name("收钱").click()
f = open("支付宝3.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
sleep(1)
driver.find_element_by_name("UIButton_back").click()
driver.find_element_by_name("卡包").click()
f = open("支付宝4.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
sleep(1)
driver.find_element_by_name("AUBarButtonItemButton_back").click()
driver.find_element_by_name("校园工作").click()
f = open("支付宝5.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
sleep(1)
driver.find_element_by_name("AUBarButtonItemButton_back").click()
driver.find_element_by_name("更多").click()
f = open("支付宝6.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
sleep(1)
driver.find_element_by_name("AUBarButtonItemButton_back").click()
driver.find_element_by_name("红包").click()
f = open("支付宝7.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
sleep(1)
driver.find_element_by_name("UIButton_back").click()
driver.find_element_by_name("电影票").click()
f = open("支付宝8.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
sleep(1)
driver.find_element_by_name("AUBarButtonItemButton_back").click()
driver.find_element_by_name("记账本").click()
f = open("支付宝9.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
sleep(1)
driver.find_element_by_name("AUBarButtonItemButton_back").click()
driver.find_element_by_name("UITabBarButton_Fortune").click()
f = open("支付宝10.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
sleep(1)
driver.find_element_by_name("UITabBarButton_Friends").click()
f = open("支付宝11.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
sleep(1)
driver.find_element_by_name("UITabBarButton_Assets").click()
f = open("支付宝12.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
sleep(1)
driver.find_element_by_name("余额").click()
f = open("支付宝13.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
sleep(1)
driver.find_element_by_name("AUBarButtonItemButton_back").click()
driver.find_element_by_name("银行卡").click()
f = open("支付宝14.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
sleep(1)

driver.find_element_by_name("AUBarButtonItemButton_back").click()
driver.find_element_by_name("蚂蚁会员").click()
f = open("支付宝15.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
sleep(1)

driver.find_element_by_name("AUBarButtonItemButton_back").click()
driver.find_element_by_name("AUBaseButton_设置").click()
f = open("支付宝16.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
sleep(1)
driver.find_element_by_name("支付设置").click()
f = open("支付宝17.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
sleep(1)
driver.find_element_by_name("UIButton_doClickNaviLeftAction:").click()
driver.find_element_by_name("密码设置").click()
f = open("支付宝18.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
sleep(1)
driver.find_element_by_name("AUBarButtonItemButton_back").click()
driver.find_element_by_name("安全中心").click()
f = open("支付宝19.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
sleep(1)
driver.find_element_by_name("UIButton_onClickedLeftItem:").click()
driver.find_element_by_name("手机号").click()
f = open("支付宝20.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
driver.quit()
