# -*- coding: utf-8 -*-

from time import sleep
from appium import webdriver

desired_caps = {}
desired_caps['automationName'] = 'XCUITest'
desired_caps['platformName'] = 'iOS'
desired_caps['platformVersion'] = '11.2.5'
desired_caps['deviceName'] = 'iPhone 5s'
desired_caps['bundleId'] = 'com.pchouse.iPhoneMag'
desired_caps['udid'] = '0f5fbbaf273ea90dce8408987e215817b66146af'
desired_caps['newCommandTimeout'] = 3600  # 1 hour
desired_caps['xcodeOrgId'] = '俊宇 裴'
desired_caps['xcodeSigningId'] = 'iPhone Developer'


# 打开Appium服务器，start server后，尝试启动被测App
driver = webdriver.Remote('http://127.0.0.1:4723/wd/hub', desired_caps)
sleep(5)
'''
f = open("居家杂志1.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
driver.find_element_by_name("攻略 ").click()
sleep(5)
f = open("居家杂志2.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
driver.tap([(10, 50)], 1)
driver.find_element_by_name("好物 ").click()
sleep(5)
f = open("居家杂志3.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
driver.tap([(10, 50)], 1)
driver.find_element_by_name("看图 ").click()
sleep(5)
f = open("居家杂志4.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
driver.tap([(10, 50)], 1)
driver.find_element_by_name("设计师 ").click()
sleep(5)
f = open("居家杂志5.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
driver.tap([(10, 50)], 1)
driver.find_element_by_name("活动 ").click()
sleep(5)
f = open("居家杂志6.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
driver.tap([(10, 50)], 1)
driver.find_element_by_name("button bookstore").click()
sleep(5)
f = open("居家杂志7.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
driver.find_element_by_name("button discover").click()
sleep(5)
f = open("居家杂志8.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
driver.find_element_by_name("button tryout").click()
sleep(5)
f = open("居家杂志9.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
'''
driver.find_element_by_name("button mycenter").click()
'''
sleep(5)
f = open("居家杂志10.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
driver.find_element_by_name("会员福利").click()
sleep(5)
f = open("居家杂志11.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
driver.tap([(10, 50)], 1)
driver.find_element_by_name("兑换积分").click()
sleep(1)
f = open("居家杂志12.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
driver.tap([(10, 50)], 1)
driver.find_element_by_name("如何注册成为会员？").click()
sleep(5)
f = open("居家杂志13.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
driver.tap([(10, 50)], 1)
driver.find_element_by_name("设置").click()
sleep(5)
f = open("居家杂志14.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
driver.find_element_by_name("意见反馈").click()
sleep(5)
f = open("居家杂志15.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
driver.tap([(10, 50)], 1)
driver.find_element_by_name("关于我们").click()
sleep(5)
f = open("居家杂志16.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
driver.tap([(10, 50)], 1)
driver.tap([(10, 50)], 1)
'''
driver.find_element_by_name("获取积分").click()
sleep(5)
f = open("居家杂志17.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
driver.find_element_by_name("注册").click()
sleep(5)
f = open("居家杂志18.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
driver.tap([(10, 50)], 1)
driver.find_element_by_name("我同意“太平洋网络服务条款及使用协议”").click()
sleep(1)
f = open("居家杂志19.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
sleep(1)
driver.tap([(10, 50)], 1)
driver.find_element_by_name("忘记密码？").click()
f = open("居家杂志20.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
driver.quit()
