# -*- coding: utf-8 -*-

from time import sleep
from appium import webdriver
import os

desired_caps = {}
desired_caps['appium-version'] = '1.6.3'
desired_caps['platformName'] = 'Android'
desired_caps['platformVersion'] = '4.4.2'
desired_caps['deviceName'] = '6&22430518&1&0001'
desired_caps['appPackage'] = 'com.eg.android.AlipayGphone'
desired_caps['appActivity'] = '.AlipayLogin'
desired_caps['noReset'] = 'true'
#desired_caps['app'] = "/Users/imbarpjy/Downloads/jinritoutiao_622.apk"

# 打开Appium服务器，start server后，尝试启动被测App
driver = webdriver.Remote('http://127.0.0.1:4723/wd/hub', desired_caps)
sleep(5)
f = open("支付宝1.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
driver.find_element_by_xpath("//*[@text='余额宝']").click()
sleep(5)
f = open("支付宝2.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
driver.find_element_by_xpath("//*[@content-desc='返回']").click()
driver.find_element_by_xpath("//*[@text='收钱']").click()
sleep(5)
f = open("支付宝3.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
driver.find_element_by_xpath("//*[@content-desc='返回']").click()
driver.find_element_by_xpath("//*[@text='卡包']").click()
sleep(5)
f = open("支付宝4.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
driver.find_element_by_xpath("//*[@content-desc='返回']").click()
driver.find_element_by_xpath("//*[@text='校园工作']").click()
sleep(5)
f = open("支付宝5.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
driver.find_element_by_xpath("//*[@content-desc='返回']").click()
driver.find_element_by_xpath("//*[@text='更多']").click()
sleep(5)
f = open("支付宝6.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
driver.find_element_by_xpath("//*[@content-desc='返回']").click()
driver.find_element_by_xpath("//*[@text='红包']").click()
sleep(4)
f = open("支付宝7.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
driver.find_element_by_xpath("//*[@content-desc='返回']").click()
driver.find_element_by_xpath("//*[@text='电影票']").click()
sleep(5)
f = open("支付宝8.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
driver.find_element_by_xpath("//*[@content-desc='返回']").click()
driver.find_element_by_xpath("//*[@text='记账本']").click()
sleep(5)
f = open("支付宝9.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
driver.find_element_by_xpath("//*[@content-desc='返回']").click()
driver.find_element_by_xpath("//*[@text='口碑']").click()
sleep(5)
f = open("支付宝10.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
driver.find_element_by_xpath("//*[@text='朋友']").click()
sleep(5)
f = open("支付宝11.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
driver.find_element_by_xpath("//*[@text='我的']").click()
sleep(5)
f = open("支付宝12.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
driver.find_element_by_xpath("//*[@text='余额']").click()
sleep(5)
f = open("支付宝13.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
driver.find_element_by_xpath("//*[@content-desc='返回']").click()
driver.find_element_by_xpath("//*[@text='银行卡']").click()
sleep(5)
f = open("支付宝14.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
driver.find_element_by_xpath("//*[@content-desc='返回']").click()
driver.find_element_by_xpath("//*[@text='蚂蚁会员']").click()
sleep(5)
f = open("支付宝15.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
driver.find_element_by_xpath("//*[@content-desc='返回']").click()
driver.find_element_by_xpath("//*[@text='设置']").click()
sleep(5)
f = open("支付宝16.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
driver.find_element_by_xpath("//*[@text='支付设置']").click()
sleep(5)
f = open("支付宝17.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
driver.find_element_by_xpath("//*[@content-desc='返回']").click()
driver.find_element_by_xpath("//*[@text='密码设置']").click()
sleep(5)
f = open("支付宝18.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
driver.find_element_by_xpath("//*[@content-desc='返回']").click()
driver.find_element_by_xpath("//*[@text='安全中心']").click()
sleep(5)
f = open("支付宝19.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
driver.find_element_by_xpath("//*[@content-desc='返回']").click()
driver.find_element_by_xpath("//*[@text='手机号']").click()
sleep(5)
f = open("支付宝20.txt",'w')
print("%s" % driver.page_source, file = f)
f.close()
driver.quit()
